---
- name: Upgrade packages
  apt:
    update_cache: yes
    upgrade: full

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: enable automatic reboot
  lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^Unattended-Upgrade::Automatic-Reboot'
    line: 'Unattended-Upgrade::Automatic-Reboot "true";'
    state: present

- name: immediately install security updates, do not wait for next shutdown
  lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^Unattended-Upgrade::InstallOnShutdown'
    line: 'Unattended-Upgrade::InstallOnShutdown "false";'
    state: present

- name: configure reboot time if /var/run/reboot-required is found
  lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^Unattended-Upgrade::Automatic-Reboot-Time'
    line: 'Unattended-Upgrade::Automatic-Reboot-Time "01:00";'
    state: present
