---
- name: Local storage basic setup
  hosts: kube_nodes
  remote_user: ansible
  become: true
  tags:
   - crypt_setup
  vars_prompt:
    - name: kube_storage_passphrase
      prompt: "Enter Disk Passphrase"
  tasks:
    - include_role:
        name: kube-storage-cryptolayer
      vars:
        kube_storage_local_raw_device: /dev/sdb
        kube_storage_local_crypted_devicename: crypted_sdb1
