---
- name: Basic account and login setup
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - account_setup
  tasks:
#    - name: Lock 'pi' account password on Raspberry (login still possible)
#      command: passwd -l pi
#      changed_when: false
    - include_role:
        name: kube-accounts
      vars:
        kube_accounts_userlist: '{{ kube_users }}'

- name: Configure network
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - network_setup
  tasks:
    - include_tasks: tasks/rubix-network-setup.yml

- name: Configure dnsmasq
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - dnsmasq_setup
  tasks:
    - name: Configure boot server
      include_role:
        name: kube-boot-server
      vars: []
