---
- name: Deploy MetalLB
  hosts: kube_nodes
  remote_user: ansible
  become: true
  tags:
    - payload_deploy_metallb
  tasks:
    - include_role:
        name: kube-payload-metallb
      vars:
        kube_payload_metallb_version: '{{ kube_metallb_version }}'
        kube_payload_metallb_iprange: '{{ kube_metallb_iprange }}'

- name: Deploy ArgoCD
  hosts: kube_nodes
  remote_user: ansible
  become: true
  tags:
   - payload_deploy_argocd
  tasks:
    - include_role:
        name: kube-payload-argocd
      vars:
        kube_payload_argocd_version: '{{ kube_argocd_version }}'
