---
- name: Upgrade packages and disable swap
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - upgrade_packages
    - disable_swap
  tasks:
    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: full
    - name: Disable swap
      include_role:
        name: kube-disable-swap

- name: Basic account and login setup
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - account_setup
  tasks:
#    - name: Lock 'pi' account password on Raspberry (login still possible)
#      command: passwd -l pi
#      changed_when: false
    - include_role:
        name: kube-accounts
      vars:
        kube_accounts_userlist: '{{ kube_users }}'

- name: Configure network
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - network_setup
  tasks:
    - include_tasks: tasks/rubix-network-setup.yml

- name: Configure PXE boot services
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - pxe_setup
    - dnsmasq_setup
  tasks:
    - name: Configure boot server
      include_role:
        name: kube-boot-server
      vars:
        kube_boot_server_ssh_keys: '{{ kube_users|map(attribute="ssh_key")|list }}'

