---
- name: Upgrade packages
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - upgrade_packages
  tasks:
    - name: Upgrade packages
      include_role:
        name: kube-upgrade-packages

- name: Disable swap
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - disable_swap
  tasks:
    - name: Disable swap
      include_role:
        name: kube-disable-swap

- name: Basic account and login setup
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - account_setup
  tasks:
    - include_role:
        name: kube-accounts
      vars:
        kube_accounts_userlist: '{{ kube_users }}'
    - name: Lock 'pi' account password (ssh login with key will still work, on console use "ansible" for login)
      command: passwd -l pi
      changed_when: false

- name: Configure network
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - network_setup
  tasks:
    - include_tasks: tasks/rubix-network-setup.yml

- name: Configure PXE boot services
  hosts: kube_install_hosts
  remote_user: ansible
  become: true
  tags:
    - pxe_setup
    - dnsmasq_setup
  tasks:
    - name: Configure boot server
      include_role:
        name: kube-boot-server
      vars:
        kube_boot_server_ssh_keys: '{{ kube_users|map(attribute="ssh_key")|list }}'
        kube_boot_server_centos_version: '{{ kube_centos_version }}'

