---
- name: Disable WLAN and Bluetooth
  copy:
    src: raspi-blacklist.conf
    dest: /etc/modprobe.d/raspi-blacklist.conf
    owner: root
    group: root
    mode: 0644
- name: Disable IPv6
  include_role:
    name: kube-disable-ipv6
- name: Configure static interfaces - add include for eth0
  lineinfile:
    path: /etc/network/interfaces
    line: '{{ item }}'
    state: present
  with_items:
    - 'source /etc/network/interfaces.d/eth0'
    - 'source /etc/network/interfaces.d/eth0.200'
- name: Configure static interfaces - remove directory-include
  lineinfile:
    path: /etc/network/interfaces
    line: '# source-directory /etc/network/interfaces.d'
    regexp: '^(# |#)?source-directory /etc/network/interfaces.d'
    state: present
- name: Copy static interface config
  copy:
    src: 'rubix-{{ item }}'
    dest: '/etc/network/interfaces.d/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - eth0
    - eth0.200
- name: Disable and stop DHCP client
  service:
    name: dhcpcd
    enabled: false
    state: stopped
- name: Add local nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: '.*nameserver.*'
    line: 'nameserver 192.168.0.8'
    state: present

