---
- name: Disable WLAN and Bluetooth
  include_role:
    name: kube-net-disable-wlan-bluetooth
- name: Disable IPv6
  include_role:
    name: kube-net-disable-ipv6
- name: Configure static interfaces with vlans
  include_role:
    name: kube-net-static-ips-two-vlans
  # todo vars
- name: Configure static dns resolver
  include_role:
    name: kube-net-static-dns-resolver
  vars:
    kube_net_static_nameserver: '{{ kube_nameserver }}'
