---
- name: Disable ssh root login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin no'
    regexp: '^PermitRootLogin'
    state: present
  notify: restart sshd

- name: Disable ssh password authentication - PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'
    regexp: '^PasswordAuthentication'
    state: present
  notify: restart sshd

- name: Disable ssh password authentication - ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'ChallengeResponseAuthentication no'
    regexp: '^ChallengeResponseAuthentication'
    state: present
  notify: restart sshd

- name: Create ansible account
  include_role:
    name: kube-account
  vars:
    kube_account_name: ansible
    kube_account_comment: Ansible Automation
    kube_account_sudo: true
    kube_account_ssh_keys: '{{ kube_accounts_userlist|map(attribute="ssh_key")|list }}'

- name: Create user accounts
  include_role:
    name: kube-account
  vars:
    kube_account_name: '{{ item.username }}'
    kube_account_comment: '{{ item.comment|default("") }}'
    kube_account_sudo: true
    kube_account_ssh_keys: '{{ [ item.ssh_key ] }}'
  with_items: '{{ kube_accounts_userlist }}'
