---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Create config directory
  file:
    name: '{{ item }}'
    owner: root
    group: root
    state: directory
  with_items:
    - /opt/dnsmasq
    - /opt/dnsmasq/etc
    - /opt/dnsmasq/tftp
    - /opt/dnsmasq/tftp/pxeboot
    - /opt/dnsmasq/conf.d
    - /opt/dnsmasq/local_hosts
- name: Create the OTHER config directory
  file:
    name: '{{ item }}'
    owner: dnsmasq
    group: root
    state: directory
  with_items:
    - /opt/dnsmasq/var
- name: Adjust dnsmasq defaults
  template:
    src: rubix-dnsmasq.j2
    dest: /etc/default/dnsmasq
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
- name: Write dnsmasq.conf
  template:
    src: rubix-dnsmasq.conf.j2
    dest: /opt/dnsmasq/etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
- name: Write hosts file
  template:
    src: rubix-dnsmasq-hosts.j2
    dest: /opt/dnsmasq/local_hosts/kube
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
- name: Write dhcp_hosts file
  template:
    src: rubix-dnsmasq-dhcp-hosts.j2
    dest: /opt/dnsmasq/etc/dhcp-hosts
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
- name: Write resolv.conf file
  template:
    src: rubix-dnsmasq-resolv.conf.j2
    dest: /opt/dnsmasq/etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

- name: Write grub.conf file
  template:
    src: rubix-dnsmasq-grub.conf.j2
    dest: /opt/dnsmasq/tftp/grub.cfg
    owner: root
    group: root
    mode: 0644

- name: enable and start dnsmasq
  service:
    name: dnsmasq
    enabled: true
    state: started

- name: Download PXE boot files
  get_url:
    url: '{{ item.url }}'
    dest: '/opt/dnsmasq/tftp/{{ item.filename }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - url: http://mirror.centos.org/centos/7.4.1708/os/x86_64/EFI/BOOT/BOOTX64.EFI
      filename: bootx64.efi
      checksum: 'sha256:1e6d991a38fe71485597585f2a1f6424bae20a8610c23668398cacc72602fd90'
    - url: http://mirror.centos.org/centos/7.4.1708/os/x86_64/EFI/BOOT/grubx64.efi
      filename: grubx64.efi
      checksum: 'sha256:9656b796ad1bbd4321285c34d8e3203cc4bb45bda64c1aabc676389b6f042e7a'
    - url: http://mirror.centos.org/centos/7.4.1708/os/x86_64/images/efiboot.img
      filename: efiboot.img
      checksum: 'sha256:78a4c33b2920471d8b21bb4b9ba4c5db8d8a2b9bf108871f8cb08b5cb6fe5801'
    - url: http://mirror.centos.org/centos/7.4.1708/os/x86_64/images/pxeboot/initrd.img
      filename: pxeboot/initrd.img
      checksum: 'sha256:5c71c0494620325c1ee919b44ac4ed4518fb43443bbf0474ff75951ea140c89c'
    - url: http://mirror.centos.org/centos/7.4.1708/os/x86_64/images/pxeboot/vmlinuz
      filename: pxeboot/vmlinuz
      checksum: 'sha256:8ede7f8d3c8f5e72f1a84713ad59b7b39211ea1af8887389cb50a189df937c6f'

