---
- name: Include dnsmasq tasks
  include_tasks: tasks-dnsmasq.yml
  tags:
    - kube_boot_server_dnsmasq

- name: Include CentOS PXE download tasks
  include_tasks: tasks-download-centos-pxe.yml
  tags:
    - kube_boot_server_download_centos_pxe

- name: Include Apache tasks
  include_tasks: tasks-apache.yml
  tags:
    - kube_boot_server_apache
