---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Listen to internal interface, only.
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen'
    line: 'Listen '
