---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Listen to internal interface, only.
  template:
    src: rubix-apache2-ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
