---
- name: Download PXE boot files
  get_url:
    url: '{{ item.url }}'
    dest: '/opt/dnsmasq/tftp/{{ item.filename }}'
    checksum: '{{ item.checksum }}'
    owner: dnsmasq
    group: root
    mode: 0644
  with_items: "{{ kube_boot_server_pxe_files }}"
