---
- name: Write grub.conf file
  template:
    src: rubix-dnsmasq-grub.conf.j2
    dest: /opt/dnsmasq/tftp/grub.cfg
    owner: dnsmasq
    group: root
    mode: 0644
  vars:
    kickstart_file: 'generic.ks'
- name: Write specific grub.conf file for any host ip with pinned ssh host keys
  template:
    src: rubix-dnsmasq-grub.conf.j2
    dest: "/opt/dnsmasq/tftp/{{ item.key }}/grub.cfg"
    owner: dnsmasq
    group: root
    mode: 0644
  vars:
    kickstart_file: 'kickstart-{{ item.key }}.ks'
  loop: "{{ kube_boot_server_ssh_host_keys|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
