---
- name: Load 802.1q kernel module now
  modprobe:
    name: 8021q
    state: present
- name: Load 802.1q kernel module again on reboot
  lineinfile:
    path: /etc/modules-load.d/010-vlan-8021q.conf
    line: '8021q'
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
- name: Render static ip config for primary interface
  template:
    src: 'centos-net-primary-interface.j2'
    dest: '/etc/sysconfig/network-scripts/ifcfg-{{ kube_net_interface }}'
    owner: root
    group: root
    mode: 0644
- name: Render static ip config for secondary interface
  template:
    src: 'centos-net-secondary-interface.j2'
    dest: '/etc/sysconfig/network-scripts/ifcfg-{{ kube_net_interface }}.{{ kube_net_secondary_vlan }}'
    owner: root
    group: root
    mode: 0644
- name: collect facts about system services
  service_facts:
  register: services_state
- name: Configure firewalld zone for primary interface
  firewalld:
    zone: '{{ kube_net_primary_zone }}'
    interface: '{{ kube_net_interface }}'
    permanent: true
    immediate: yes
    state: enabled
  when: kube_net_primary_zone is defined and services_state.ansible_facts.services['firewalld.service'].state == "running"
- name: Configure firewalld zone for secondary interface
  firewalld:
    zone: '{{ kube_net_secondary_zone }}'
    interface: '{{ kube_net_interface }}.{{ kube_net_secondary_vlan }}'
    permanent: true
    immediate: yes
    state: enabled
  when: kube_net_secondary_zone is defined and services_state.ansible_facts.services['firewalld.service'].state == "running"
- name: Stop and disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

