---
- name: Announce nameserver to resolvconf
  lineinfile:
    path: /etc/resolvconf.conf
    regexp: '^(# |#)?name_servers='
    line: 'name_servers={{ kube_net_static_nameserver }}'
  when: ansible_os_family == "Debian"
- name: Disable resolvconf
  lineinfile:
    path: /etc/resolvconf.conf
    regexp: '^(# |#)?resolvconf='
    line: 'resolvconf=NO'
    state: present
  when: ansible_os_family == "Debian"
- name: Statically set local nameserver(s)
  template:
    src: resolv.conf.j2
    dest: '/etc/resolv.conf'
    owner: root
    group: root
    mode: 0644
- name: Hard configure the host name
  hostname:
    name: '{{ inventory_hostname }}'
