---
- name: Disable IPv6
  copy:
    src: sysctl-disable-ipv6.conf
    dest: /etc/sysctl.d/80-disable-ipv6.conf
    owner: root
    group: root
    mode: 0644
- name: restrict sshd to ipv4 to keep X forwarding functional
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AddressFamily inet'
    regexp: '^#?AddressFamily'
    state: present
  notify: restart sshd
