---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  listen: restart dnsmasq
- name: restart apache2
  service:
    name: apache2
    state: restarted
  listen: restart apache2
